### ISSUE TITLE
Added vehicles / Barriers not showing up.

### ISSUE THREAD

**Issue by Rennschnitzl** [Zaraka/GruntArbiter#1]
Win7 - x64
Release: 1.0.0

Steps to reproduce:
- start with exe
- create new campaign
- keep default name: "SampleCampaign" -> ok
- add player "John Doe" -> ok
- create new battle -> ok
- enter initiative "1" -> ok
- add vehicle -> vehicle -> groundcraft -> bike -> dodge scoot -> ok

no vehicles showing up.

save file renamed to txt because github.
[novehicle.txt](https://github.com/Zaraka/GruntArbiter/files/1355380/novehicle.txt)

file -> save campaign and file -> open campaign adds the view for vehicles.

same problem for barriers. I have to save and load the campaign for barriers to show up.

**Comment by Zaraka** [comment]
Should be working in master. 
Looks like in older version of JDK (used while building Windows version) there's quite a few bugs in javafx.Bindings package. I should update to Java 9 as soon as it will be available on Travis & Appveyor.

However I've noticed some other theme related bugs in Windows, I will do another release after I fix them.
